AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Project using some AWS serveless services
Parameters:
  ImagesBucket:
    Type: String
    Default: images-bucket-dpp-new-2
Globals:
  Function:
    Timeout: 50
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: '''OPTIONS,GET,POST,PUT,DELETE'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
        AllowOrigin: '''*'''
      Auth:
        Authorizers:
          CustomLambdaTokenAuthorizer:
            FunctionArn:
              Fn::GetAtt:
              - ValidateTokenFunction
              - Arn
            Identity:
              Header: Authorization
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/e69c9f8a1fcf3437e7abc9bbf11bee0a
      Handler: authorizer.basiclogin
      Runtime: nodejs8.10
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /login
            Method: post
  ValidateTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/e69c9f8a1fcf3437e7abc9bbf11bee0a
      Handler: authorizer.validateToken
      Runtime: nodejs8.10
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/e69c9f8a1fcf3437e7abc9bbf11bee0a
      Handler: usersCRUD.get
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
      Events:
        GetUserPath:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users/{resourceId}
            Method: get
            Auth:
              Authorizer: CustomLambdaTokenAuthorizer
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/e69c9f8a1fcf3437e7abc9bbf11bee0a
      Handler: usersCRUD.create
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
          ENTITY_ID_FIELD: document.value
      Events:
        PostRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users
            Method: post
  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/e69c9f8a1fcf3437e7abc9bbf11bee0a
      Handler: usersCRUD.update
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
      Events:
        PutRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users/{resourceId}
            Method: put
            Auth:
              Authorizer: CustomLambdaTokenAuthorizer
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/e69c9f8a1fcf3437e7abc9bbf11bee0a
      Handler: usersCRUD.delete
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
      Events:
        PutRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users/{resourceId}
            Method: delete
            Auth:
              Authorizer: CustomLambdaTokenAuthorizer
  PublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/e69c9f8a1fcf3437e7abc9bbf11bee0a
      Handler: mediaCRUD.upload
      Runtime: nodejs8.10
      Timeout: 60
      Policies:
      - S3CrudPolicy:
          BucketName:
            Fn::Sub: ${ImagesBucket}
      Environment:
        Variables:
          S3_bucket:
            Ref: ImagesBucket
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /upload
            Method: post
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: usersTable
      PrimaryKey:
        Name: id
        Type: String
      Tags:
        Department: Middleware
        AppType: Serverless
      SSESpecification:
        SSEEnabled: true
  ImagesS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: ImagesBucket
Outputs:
  ApiURL:
    Description: API URL
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/
