AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Project using some AWS serveless services
Globals:
  Function:
    Timeout: 50
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: CustomLambdaTokenAuthorizer
        Authorizers:
          CustomLambdaTokenAuthorizer:
            FunctionArn:
              Fn::GetAtt:
              - ValidateTokenFunction
              - Arn
            Identity:
              Header: Authorization
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/83634c27bd2dfe3341444df6090621b5
      Handler: authorizer.basiclogin
      Runtime: nodejs8.10
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /login
            Method: post
            Auth:
              Authorizer: NONE
  ValidateTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/83634c27bd2dfe3341444df6090621b5
      Handler: authorizer.validateToken
      Runtime: nodejs8.10
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/83634c27bd2dfe3341444df6090621b5
      Handler: usersCRUD.get
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
      Events:
        GetUserPath:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users/{resourceId}
            Method: get
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/83634c27bd2dfe3341444df6090621b5
      Handler: usersCRUD.create
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
          ENTITY_ID_FIELD: document.value
      Events:
        PostRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users
            Method: post
  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/83634c27bd2dfe3341444df6090621b5
      Handler: usersCRUD.update
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
      Events:
        PutRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users/{resourceId}
            Method: put
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-demo-bucket-dpp/83634c27bd2dfe3341444df6090621b5
      Handler: usersCRUD.delete
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
      Events:
        PutRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /users/{resourceId}
            Method: delete
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: usersTable
      PrimaryKey:
        Name: id
        Type: String
      Tags:
        Department: Middleware
        AppType: Serverless
      SSESpecification:
        SSEEnabled: true
Outputs:
  ApiURL:
    Description: API URL
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/
